import User from "../models/User.js";
import Product from "../models/Product.js";
import bcrypt from "bcryptjs";
import { products } from "../ultis/dummy.js";
import Order from "../models/Order.js";
const users = [
  {
    displayName: "NGUYEN VAN DUONG",
    username: "0349157186",
    password: "123456",
    phone: "0349157186",
    address: "Nhà văn hóa trần xá",
    cityName: "Bắc Ninh",
    districtName: "Huyện Yên Phong",
    wardFullName: "Thị trấn Chờ",
  },
  {
    displayName: "NGUYEN HUU QUY",
    username: "0989976767",
    password: "123456",
    phone: "0989976767",
    address: "thôn hộ vệ",
    cityName: "Bắc Ninh",
    districtName: "Huyện Tiên Du",
    wardFullName: "Xã Lạc Vệ",
  },
  {
    displayName: "NGUYEN VAN VIET",
    username: "0982978653",
    password: "123456",
    phone: "0982978653",
    address:
      "Phường đồng kỵ_phố thành nhàn_từ sơn_bắc ninh,Từ Sơn,Tỉnh Bắc Ninh",
    cityName: "Bắc Ninh",
    districtName: "Thị xã Từ Sơn",
    wardFullName: "Phường Đông Ngàn",
  },
  {
    displayName: "NGUYEN VAN PHU VINH",
    username: "0374529221",
    password: "123456",
    phone: "0374529221",
    address: "99 đường Huỳnh Cương",
    cityName: "Cần Thơ",
    districtName: "Quận Ninh Kiều",
    wardFullName: "Phường An Cư",
  },
  {
    displayName: "NGO THAI HOC",
    username: "0337999932",
    password: "123456",
    phone: "0337999932",
    address:
      "Tri Thủy - Tri Hải - Ninh Hải - Ninh Thuận,Ninh Hải,Tỉnh Ninh Thuận",
    cityName: "Ninh Thuận",
    districtName: "Huyện Ninh Hải",
    wardFullName: "Xã Tri Hải",
  },
  {
    displayName: "NGUYEN THI HA THU",
    username: "0763540058",
    password: "123456",
    phone: "0763540058",
    address:
      "Khu giếng mụi phường cộng hoà thị xã quảng yên tỉnh quảng ninh,Quảng Yên,Tỉnh Quảng Ninh",
    cityName: "Quảng Ninh",
    districtName: "Thị xã Quảng Yên",
    wardFullName: "Phường Cộng Hòa",
  },
  {
    displayName: "NGUYEN THI NGA",
    username: "0989598666",
    password: "123456",
    phone: "0989598666",
    address: "91 Nguyễn đăng sở,Bắc Ninh,Tỉnh Bắc Ninh",
    cityName: "Bắc Ninh",
    districtName: "Thị xã Từ Sơn",
    wardFullName: "Phường Châu Khê",
  },
  {
    displayName: "BAC THI TUYET",
    username: "0342595680",
    password: "123456",
    phone: "0342595680",
    address: "Khu 9 tiên phú,Phù Ninh,Tỉnh Phú Thọ",
    cityName: "Phú Thọ",
    districtName: "Huyện Phù Ninh",
    wardFullName: "Xã Tiên Phú",
  },
  {
    displayName: "PHAM KHAC MINH TUAN",
    username: "0329822228",
    password: "123456",
    phone: "0329822228",
    address: "Trường đại học công nghiệp cơ sở 2,Quảng Yên,Tỉnh Quảng Ninh",
    cityName: "Quảng Ninh",
    districtName: "Thị xã Từ Sơn",
    wardFullName: "Phường Cộng Hòa",
  },
  {
    displayName: "PHAM VAN LUC",
    username: "0976882733",
    password: "123456",
    phone: "0976882733",
    address: "Xóm 3c_ xã khánh nhạc,Yên Khánh,Tỉnh Ninh Bình",
    cityName: "Ninh Bình",
    districtName: "Huyện Yên Khánh",
    wardFullName: "Xã Khánh Nhạc",
  },
  {
    displayName: "NGUYEN THI NHAN",
    username: "0964885912",
    password: "123456",
    phone: "0964885912",
    address: "Xom4 ngọc động gia phong,Nho Quan,Tỉnh Ninh Bình",
    cityName: "Ninh Bình",
    districtName: "Huyện Nho Quan",
    wardFullName: "Xã Lạng Phong",
  },
  {
    displayName: "BUI VAN SON",
    username: "0909500034",
    password: "123456",
    phone: "0909500034",
    address: "40 lế Ninh,Quận8,Hồ Chí Minh",
    cityName: "Hồ Chí Minh",
    districtName: "Quận 8",
    wardFullName: "Phường 1",
  },
  {
    displayName: "HA BAO CHUNG",
    username: "0398199667",
    password: "123456",
    phone: "0398199667",
    address:
      "Nhà số 6 ngõ số 1 thôn Sơn Nam, xã Nam Sơn,Bắc Ninh,Tỉnh Bắc Ninh",
    cityName: "Bắc Ninh",
    districtName: "Thành phố Bắc Ninh",
    wardFullName: "Xã Nam Sơn",
  },
  {
    displayName: "NGUYEN THI PHUONG THAO",
    username: "0962650967",
    password: "123456",
    phone: "0962650967",
    address: "Xóm la hùng thôn la xuyên xã yên ninh,Ý Yên,Tỉnh Nam Định",
    cityName: "Nam Định",
    districtName: "Huyện Ý Yên",
    wardFullName: "Xã Yên Tân",
  },
  {
    displayName: "LE MINH THANH",
    username: "0795419392",
    password: "123456",
    phone: "0795419392",
    address:
      "Số 1, Đường Lê Chân, KDC91B, An Khánh, Ninh Kiều, Cần Thơ,Ninh Kiều,Cần Thơ",
    cityName: "Cần Thơ",
    districtName: "Quận Ninh Kiều",
    wardFullName: "Phường An Khánh",
  },
  {
    displayName: "LY MINH CHANH",
    username: "0766841771",
    password: "123456",
    phone: "0766841771",
    address:
      "Địa chỉ 49X1/7 Nguyễn Văn Linh, P An Khánh, Q Ninh kiều, TPCT (,Ninh Kiều,Cần Thơ",
    cityName: "Cần Thơ",
    districtName: "Quận Ninh Kiều",
    wardFullName: "Phường An Khánh",
  },
  {
    displayName: "NGUYEN HOANG NHAT DUY",
    username: "0968337075",
    password: "123456",
    phone: "0968337075",
    address: "số 03, ấp Cây Da, xã Hiệp Thạnh,Gò Dầu,Tỉnh Tây Ninh",
    cityName: "Tây Ninh",
    districtName: "Huyện Gò Dầu",
    wardFullName: "Xã Hiệp Thạnh",
  },
  {
    displayName: "NGUYEN THANH HAI",
    username: "0857282555",
    password: "123456",
    phone: "0857282555",
    address: "Thôn thành bác xã văn phú,Nho Quan,Tỉnh Ninh Bình",
    cityName: "Ninh Bình",
    districtName: "Huyện Nho Quan",
    wardFullName: "Xã Văn Phú",
  },
  {
    displayName: "DUONG VAN QUANG",
    username: "0869089660",
    password: "123456",
    phone: "0869089660",
    address: "chợ tiền phường khắc niệm,Bắc Ninh,Tỉnh Bắc Ninh",
    cityName: "Bắc Ninh",
    districtName: "Thành phố Bắc Ninh",
    wardFullName: "Phường Khắc Niệm",
  },
  {
    displayName: "NGUYEN VAN LINH",
    username: "0962625263",
    password: "123456",
    phone: "0962625263",
    address: "Thôn núi đông xã hoàn sơn,Tiên Du,Tỉnh Bắc Ninh",
    cityName: "Bắc Ninh",
    districtName: "Huyện Tiên Du",
    wardFullName: "Xã Hoàn Sơn",
  },
  {
    displayName: "QUACH VAN HOANG",
    username: "0384726555",
    password: "123456",
    phone: "0384726555",
    address:
      "Công ty cổ phần Hanacans, khu đô thị Hanaka, Phường Đồng Nguyên,Từ Sơn,Tỉnh Bắc Ninh",
    cityName: "Bắc Ninh",
    districtName: "Thị xã Từ Sơn",
    wardFullName: "Phường Đồng Nguyên",
  },
  {
    displayName: "VU TRONG HUY",
    username: "0328128167",
    password: "123456",
    phone: "0328128167",
    address: "Phường hả tu,Hạ Long,Tỉnh Quảng Ninh",
    cityName: "Quảng Ninh",
    districtName: "Thành phố Hạ Long",
    wardFullName: "Phường Hà Tu",
  },
  {
    displayName: "DUONG DINH TOAN",
    username: "0372069735",
    password: "123456",
    phone: "0372069735",
    address: "Hồi quan tương giang từ sơn bắc ninh,Từ Sơn,Tỉnh Bắc Ninh",
    cityName: "Bắc Ninh",
    districtName: "Thị xã Từ Sơn",
    wardFullName: "Xã Tương Giang",
  },
  {
    displayName: "NGUYEN THI THIEM",
    username: "0985631466",
    password: "123456",
    phone: "0985631466",
    address:
      "Số 27 khu 3b trung tâm thương mại Lim, thị trấn lim,Tiên Du,Tỉnh Bắc Ninh",
    cityName: "Bắc Ninh",
    districtName: "Huyện Tiên Du",
    wardFullName: "Thị trấn Lim",
  },
  {
    displayName: "LE THI THU HUYEN",
    username: "0972270456",
    password: "123456",
    phone: "0972270456",
    address:
      "Xóm 7, nam cường, khánh cường, yên khánh, ninh bình,Yên Khánh,Tỉnh Ninh Bình",
    cityName: "Ninh Bình",
    districtName: "Huyện Yên Khánh",
    wardFullName: "Xã Khánh Cường",
  },
  {
    displayName: "TRAN TUAN ANH",
    username: "0888812909",
    password: "123456",
    phone: "0888812909",
    address: "Xóm 1 trực thắng, trực ninh, Nam Định,Trực Ninh,Tỉnh Nam Định",
    cityName: "Nam Định",
    districtName: "Huyện Trực Ninh",
    wardFullName: "Xã Trực Thắng",
  },
  {
    displayName: "NGUYEN VAN MINH",
    username: "0966328993",
    password: "123456",
    phone: "0966328993",
    address:
      "Ninh khánh thị trấn nếnh việt yên bắc giang,Việt Yên,Tỉnh Bắc Giang",
    cityName: "Bắc Giang",
    districtName: "Huyện Việt Yên",
    wardFullName: "Thị trấn Nếnh",
  },
  {
    displayName: "NGUYEN THANH DUY",
    username: "0376111352",
    password: "123456",
    phone: "0376111352",
    address: "Ấp xóm bố xã hiệp thạnh gò dầu tây ninh,Gò Dầu,Tỉnh Tây Ninh",
    cityName: "Tây Ninh",
    districtName: "Huyện Gò Dầu",
    wardFullName: "Xã Hiệp Thạnh",
  },
  {
    displayName: "LY ANH XUAN",
    username: "0936513825",
    password: "123456",
    phone: "0936513825",
    address:
      "Club bi-a 1990 cổng trường mầm non hà khẩu,Hạ Long,Tỉnh Quảng Ninh",
    cityName: "Cần Thơ",
    districtName: "Thành phố Hạ Long",
    wardFullName: "Phường Hà Khẩu",
  },
  {
    displayName: "DOAN CONG DANH",
    username: "0332857936",
    password: "123456",
    phone: "0332857936",
    address:
      "Thôn phú mỹ xã tam phước phú ning quảng nam,Phú Ninh,Tỉnh Quảng Nam",
    cityName: "Quảng Nam",
    districtName: "Huyện Phú Ninh",
    wardFullName: "Xã Tam Phước",
  },
  {
    displayName: "DINH THI DUNG",
    username: "0762312215",
    password: "123456",
    phone: "0762312215",
    address:
      "Tổ1 phương an phương nam thành phố uông bí,Uông Bí,Tỉnh Quảng Ninh",
    cityName: "Quảng Ninh",
    districtName: "Thành phố Uông Bí",
    wardFullName: "Phường Phương Nam",
  },
  {
    displayName: "NGUYEN HUU MINH",
    username: "0978988505",
    password: "123456",
    phone: "0978988505",
    address: "Đội 4 trực thuận trực ninh nam định,Trực Ninh,Tỉnh Nam Định",
    cityName: "Nam Định",
    districtName: "Huyện Trực Ninh",
    wardFullName: "Xã Trực Thuận",
  },
  {
    displayName: "NGUYEN VAN TRUONG",
    username: "0941898795",
    password: "123456",
    phone: "0941898795",
    address: "Lãng nội, gia lập, gia viễn, ninh bình,Gia Viễn,Tỉnh Ninh Bình",
    cityName: "Ninh Bình",
    districtName: "Huyện Gia Viễn",
    wardFullName: "Xã Gia Lập",
  },
  {
    displayName: "TUONG LONG NHAT",
    username: "0705745655",
    password: "123456",
    phone: "0705745655",
    address: "Số nhà 27 tổ 2 liên phương phương đông,Uông Bí,Tỉnh Quảng Ninh",
    cityName: "Quảng Ninh",
    districtName: "Thành phố Uông Bí",
    wardFullName: "Phường Phương Đông",
  },
  {
    displayName: "NGUYEN TAN VINH",
    username: "0356004528",
    password: "123456",
    phone: "0356004528",
    address: "Thôn Vân Thạch Xã Ninh Xuân,Ninh Hòa,Tỉnh Khánh Hòa",
    cityName: "Khánh Hòa",
    districtName: "Thị xã Ninh Hòa",
    wardFullName: "Xã Ninh Xuân",
  },
  {
    displayName: "NGUYEN TIEN DAT",
    username: "0386668236",
    password: "123456",
    phone: "0386668236",
    address: "Công ty may weitai - việt hưng,Hạ Long,Tỉnh Quảng Ninh",
    cityName: "Quảng Ninh",
    districtName: "Thành phố Hạ Long",
    wardFullName: "Phường Việt Hưng",
  },
  {
    displayName: "DO HUY HOANG",
    username: "0969938633",
    password: "123456",
    phone: "0969938633",
    address: "Khu 7b phường cẩm phú cẩm phả quảng ninh,Cẩm Phả,Tỉnh Quảng Ninh",
    cityName: "Quảng Ninh",
    districtName: "Thành phố Cẩm Phả",
    wardFullName: "Phường Cẩm Phú",
  },
  {
    displayName: "VU HUU SINH",
    username: "0354321068",
    password: "123456",
    phone: "0354321068",
    address: "Tổ 6 khu 7 giếng đáy hạ Long,Hạ Long,Tỉnh Quảng Ninh",
    cityName: "Quảng Ninh",
    districtName: "Thành phố Hạ Long",
    wardFullName: "Phường Giếng Đáy",
  },
  {
    displayName: "BUI VAN THIEN",
    username: "0989364311",
    password: "123456",
    phone: "0989364311",
    address: "Thôn mão 2 xã chi lăng quễ võ bắc ninh,Quế Võ,Tỉnh Bắc Ninh",
    cityName: "Bắc Ninh",
    districtName: "Huyện Quế Võ",
    wardFullName: "Xã Chi Lăng",
  },
  {
    displayName: "BUI PHUC LUONG",
    username: "0964284283",
    password: "123456",
    phone: "0964284283",
    address: "Thôn Trường Thọ Xã Phước Hậu,Ninh Phước,Tỉnh Ninh Thuận",
    cityName: "Ninh Thuận",
    districtName: "Huyện Ninh Phước",
    wardFullName: "Xã Phước Hậu",
  },
  {
    displayName: "NGUYEN VAN DUY",
    username: "0386288747",
    password: "123456",
    phone: "0386288747",
    address:
      "Số 1, xã Phan . Huyện dương minh châu. Tây ninh,Dương Minh Châu,Tỉnh Tây Ninh",
    cityName: "Tây Ninh",
    districtName: "Huyện Dương Minh Châu",
    wardFullName: "Xã Phan",
  },
  {
    displayName: "NGUYEN TIEN DUNG",
    username: "0395454471",
    password: "123456",
    phone: "0395454471",
    address: "Tổ 4 khu 3 Vàng Danh,Uông Bí,Tỉnh Quảng Ninh",
    cityName: "Quảng Ninh",
    districtName: "Thành phố Uông Bí",
    wardFullName: "Phường Vàng Danh",
  },
  {
    displayName: "PHAM THE HIEU",
    username: "0969812995",
    password: "123456",
    phone: "0969812995",
    address:
      "Số 3 tổ 3 khu 6c Phường Cẩm Trung Thành Phố Cẩm Phả Tỉnh Quảng Ninh,Cẩm Phả,Tỉnh Quảng Ninh",
    cityName: "Quảng Ninh",
    districtName: "Thành phố Cẩm Phả",
    wardFullName: "Phường Cẩm Trung",
  },
  {
    displayName: "BUI THI VAN ANH",
    username: "0963909587",
    password: "123456",
    phone: "0963909587",
    address: "Thôn ngọc thự-xã gia tường,Nho Quan,Tỉnh Ninh Bình",
    cityName: "Ninh Bình",
    districtName: "Huyện Nho Quan",
    wardFullName: "Xã Gia Tường",
  },
  {
    displayName: "HA MINH PHONG",
    username: "0862205505",
    password: "123456",
    phone: "0862205505",
    address:
      "Thôn 12 xã hạ long huyện vân đồn tỉnh quảng ninh,Vân Đồn,Tỉnh Quảng Ninh",
    cityName: "Quảng Ninh",
    districtName: "Huyện Vân Đồn",
    wardFullName: "Xã Hạ Long",
  },
  {
    displayName: "NGUYEN CONG HOAN",
    username: "0936009268",
    password: "123456",
    phone: "0936009268",
    address: "Khu 9 thị trấn cái rồng,Hạ Long,Tỉnh Quảng Ninh",
    cityName: "Quảng Ninh",
    districtName: "Thành phố Hạ Long",
    wardFullName: "Phường Bãi Cháy",
  },
  {
    displayName: "PHAM VAN NAM",
    username: "0398421055",
    password: "123456",
    phone: "0398421055",
    address: "22 hội phố đông hải,Tiên Yên,Tỉnh Quảng Ninh",
    cityName: "Quảng Ninh",
    districtName: "Huyện Tiên Yên",
    wardFullName: "Xã Đông Hải",
  },
  {
    displayName: "PHAM CONG TAN",
    username: "0797819494",
    password: "123456",
    phone: "0797819494",
    address:
      "Gần Tịnh xá ngọc bình, thôn Long Bình 1, Xã An Hải,Ninh Phước,Tỉnh Ninh Thuận",
    cityName: "Ninh Thuận",
    districtName: "Huyện Ninh Phước",
    wardFullName: "Xã An Hải",
  },
  {
    displayName: "DOAN VAN DO",
    username: "0766329058",
    password: "123456",
    phone: "0766329058",
    address: "Tế cầu hồng đức ninh giang hải dương,Ninh Giang,Tỉnh Hải Dương",
    cityName: "Hải Dương",
    districtName: "Huyện Ninh Giang",
    wardFullName: "Xã Hồng Đức",
  },
  {
    displayName: "TRAN THIEN TRUNG",
    username: "0385911813",
    password: "123456",
    phone: "0385911813",
    address:
      "Trà sữa Vi Vi Lê, Xã An Thái Đông, Huyện Cái Bè, Tỉnh Tiền Giang,Cái Bè,Tỉnh Tiền Giang",
    cityName: "Tiền Giang",
    districtName: "Huyện Cái Bè",
    wardFullName: "Xã An Thái Đông",
  },
  {
    displayName: "BUI VAN AN",
    username: "0585426509",
    password: "123456",
    phone: "0585426509",
    address: "Nghĩa trụ , văn giang, Hưng Yên,Văn Giang,Tỉnh Hưng Yên",
    cityName: "Hưng Yên",
    districtName: "Huyện Văn Giang",
    wardFullName: "Thị trấn Văn Giang",
  },
  {
    displayName: "NGO HOANG VY",
    username: "0847120605",
    password: "123456",
    phone: "0847120605",
    address: "Thôn Giang Sơn- Xã Hoà Hiệp,Cư Kuin,Tỉnh Đắk Lắk",
    cityName: "Đắk Lắk",
    districtName: "Huyện Cư Kuin",
    wardFullName: "Xã Hòa Hiệp",
  },
  {
    displayName: "PHAN HUU NGAN",
    username: "0915104088",
    password: "123456",
    phone: "0915104088",
    address: "522 Võ Thị Sáu, Phường Mỹ Xuyên,Long Xuyên,Tỉnh An Giang",
    cityName: "An Giang",
    districtName: "Thành phố Long Xuyên",
    wardFullName: "Phường Mỹ Xuyên",
  },
  {
    displayName: "NGUYEN THANH NGHIA",
    username: "0917157543",
    password: "123456",
    phone: "0917157543",
    address:
      "157 Đường cặp kênh Mại văn lý, ấp Ruộng Cạn xã Bình Nghị huyện Gò Công Đông,Gò Công Đông,Tỉnh Tiền Giang",
    cityName: "Tiền Giang",
    districtName: "Huyện Gò Công Đông",
    wardFullName: "Xã Bình Nghị",
  },
  {
    displayName: "VU VAN QUY",
    username: "0886606244",
    password: "123456",
    phone: "0886606244",
    address: "82 đường hòa Sơn,Bắc Giang,Tỉnh Bắc Giang",
    cityName: "Bắc Giang",
    districtName: "Thành phố Bắc Giang",
    wardFullName: "Phường Trần Nguyên Hãn",
  },
  {
    displayName: "NGUYEN HUY HOANG",
    username: "0377762711",
    password: "123456",
    phone: "0377762711",
    address: "Nam ngạn,Việt Yên,Tỉnh Bắc Giang",
    cityName: "Bắc Giang",
    districtName: "Huyện Việt Yên",
    wardFullName: "Xã Hương Mai",
  },
  {
    displayName: "LE XUAN CHUYEN",
    username: "0397149179",
    password: "123456",
    phone: "0397149179",
    address:
      "Khu Công Nghiệp Tân Hương- Châu Thành- tiền Giang,Châu Thành,Tỉnh Tiền Giang",
    cityName: "Tiền Giang",
    districtName: "Huyện Châu Thành(TG)",
    wardFullName: "Thị trấn Tân Hiệp",
  },
  {
    displayName: "TRINH TAN QUYEN",
    username: "0974645436",
    password: "123456",
    phone: "0974645436",
    address: "Ấp Phú lợi xã Phú Hữu,Châu Thành,Tỉnh Hậu Giang",
    cityName: "Hậu Giang",
    districtName: "Huyện Châu Thành(HG)",
    wardFullName: "Xã Phú Hữu",
  },
  {
    displayName: "VU THANH TUNG",
    username: "0969288238",
    password: "123456",
    phone: "0969288238",
    address: "Thôn diệm dương đông xã trà Giang,Kiến Xương,Tỉnh Thái Bình",
    cityName: "Thái Bình",
    districtName: "Huyện Kiến Xương",
    wardFullName: "Xã Trà Giang",
  },
  {
    displayName: "TO HUYNH HUONG THOM",
    username: "0906324038",
    password: "123456",
    phone: "0906324038",
    address:
      "38 Hưng Thạnh, Đạo Hữu cảnh , Châu Phú. An Giang,Châu Phú,Tỉnh An Giang",
    cityName: "An Giang",
    districtName: "Huyện Châu Phú",
    wardFullName: "Xã Đào Hữu Cảnh",
  },
  {
    displayName: "NGUYEN VAN NGOC",
    username: "0981799320",
    password: "123456",
    phone: "0981799320",
    address:
      "Nhà văn hóa vân cốc 4 xã vân trung huyện việt yên tỉnh bắc giang,Việt Yên,Tỉnh Bắc Giang",
    cityName: "Bắc Giang",
    districtName: "Huyện Việt Yên",
    wardFullName: "Xã Vân Trung",
  },
  {
    displayName: "NGUYEN TRONG NGHIA",
    username: "0344444738",
    password: "123456",
    phone: "0344444738",
    address:
      "Chợ Tân thành xã Vĩnh thành huyện châu thành an giang,Châu Thành,Tỉnh An Giang",
    cityName: "An Giang",
    districtName: "Huyện Châu Thành(AG)",
    wardFullName: "Xã Vĩnh Thành",
  },
  {
    displayName: "NGUYEN VAN HAI",
    username: "0866110520",
    password: "123456",
    phone: "0866110520",
    address: "Thôn nhuệ giang xã đào dương,Ân Thi,Tỉnh Hưng Yên",
    cityName: "Hưng Yên",
    districtName: "Huyện Ân Thi",
    wardFullName: "Xã Đào Dương",
  },
  {
    displayName: "DANG TRAN NHU LINH",
    username: "0797646456",
    password: "123456",
    phone: "0797646456",
    address: "Khu phố 6tt an thới,Phú Quốc,Tỉnh Kiên Giang",
    cityName: "Kiên Giang",
    districtName: "Huyện Đảo Phú Quốc",
    wardFullName: "Thị trấn An Thới",
  },
  {
    displayName: "HUYNH HONG DUYEN",
    username: "0907239596",
    password: "123456",
    phone: "0907239596",
    address: "56 tổ 2 ấp chợ xã an thái đông,Cái Bè,Tỉnh Tiền Giang",
    cityName: "Tiền Giang",
    districtName: "Huyện Cái Bè",
    wardFullName: "Xã An Thái Đông",
  },
  {
    displayName: "HOANG MANH TUNG",
    username: "0973546016",
    password: "123456",
    phone: "0973546016",
    address:
      "Công Ty Newwing 1, Hồng Hải, Khu Công Nghiệp Vân Trung, Xã Vân Trung,Việt Yên,Tỉnh Bắc Giang",
    cityName: "Bắc Giang",
    districtName: "Huyện Việt Yên",
    wardFullName: "Xã Vân Trung",
  },
  {
    displayName: "NGUYEN VAN HUNG",
    username: "0972743567",
    password: "123456",
    phone: "0972743567",
    address:
      "xóm 3 - Thôn Yên Ninh- Thị trấn Nếnh- Việt Yên- Bắc Giang,Việt Yên,Tỉnh Bắc Giang",
    cityName: "Bắc Giang",
    districtName: "Huyện Việt Yên",
    wardFullName: "Thị trấn Nếnh",
  },
  {
    displayName: "DUONG VAN TU",
    username: "0971690933",
    password: "123456",
    phone: "0971690933",
    address: "Tổ  dân phố 3 Thị Trấn Kép,Lạng Giang,Tỉnh Bắc Giang",
    cityName: "Bắc Giang",
    districtName: "Huyện Lạng Giang",
    wardFullName: "Thị trấn Kép",
  },
  {
    displayName: "VU DINH KIEN",
    username: "0385786966",
    password: "123456",
    phone: "0385786966",
    address:
      "Tòa nhà vak quang châu việt yên bắc giang,Việt Yên,Tỉnh Bắc Giang",
    cityName: "Bắc Giang",
    districtName: "Huyện Việt Yên",
    wardFullName: "Xã Việt Tiến",
  },
  {
    displayName: "LO XUAN HOA",
    username: "0987768991",
    password: "123456",
    phone: "0987768991",
    address: "19 ba sơn,Chi Lăng,Tỉnh Lạng Sơn",
    cityName: "Lạng Sơn",
    districtName: "Huyện Chi Lăng",
    wardFullName: "Thị trấn Chi Lăng",
  },
  {
    displayName: "NGUYEN DINH KHIEM",
    username: "0334797857",
    password: "123456",
    phone: "0334797857",
    address: "Tà Pịac,Hoàng Việt,Văn Lãng,Lạng Sơn,Văn Lãng,Tỉnh Lạng Sơn",
    cityName: "Lạng Sơn",
    districtName: "Huyện Văn Lãng",
    wardFullName: "Xã Hoàng Việt",
  },
  {
    displayName: "NGUYEN HUU THAO",
    username: "0377567102",
    password: "123456",
    phone: "0377567102",
    address:
      "số nhà 23 ngõ 2 khối 5 phường vĩnh trại tp lạng sơn,Lạng Sơn,Tỉnh Lạng Sơn",
    cityName: "Lạng Sơn",
    districtName: "Thành phố Lạng Sơn",
    wardFullName: "Phường Vĩnh Trại",
  },
  {
    displayName: "NONG VAN CO",
    username: "0389702998",
    password: "123456",
    phone: "0389702998",
    address: "32/38 Lê Quý Đôn,Lạng Sơn,Tỉnh Lạng Sơn",
    cityName: "Lạng Sơn",
    districtName: "Thành phố Lạng Sơn",
    wardFullName: "Phường Hoàng Văn Thụ",
  },
  {
    displayName: "LOC VAN PHUC",
    username: "0346515481",
    password: "123456",
    phone: "0346515481",
    address: "Long giang xuân long cao lộc lạng Sơn,Cao Lộc,Tỉnh Lạng Sơn",
    cityName: "Lạng Sơn",
    districtName: "Huyện Cao Lộc",
    wardFullName: "Xã Xuân Long",
  },
  {
    displayName: "NGUYEN VAN HIEU",
    username: "0356103490",
    password: "123456",
    phone: "0356103490",
    address: "thôn thịnh hoà xã hoà lạc,Hữu Lũng,Tỉnh Lạng Sơn",
    cityName: "Lạng Sơn",
    districtName: "Huyện Hữu Lũng",
    wardFullName: "Xã Hòa Lạc",
  },
  {
    displayName: "VI THANH TUNG",
    username: "0789373338",
    password: "123456",
    phone: "0789373338",
    address: "Số 79 đại huề, tt đồng mỏ,Chi Lăng,Tỉnh Lạng Sơn",
    cityName: "Lạng Sơn",
    districtName: "Huyện Chi Lăng",
    wardFullName: "Thị trấn Đồng Mỏ",
  },
  {
    displayName: "DOAN THANH TUAN",
    username: "0966839148",
    password: "123456",
    phone: "0966839148",
    address: "khu đô thị vân canh , cây xăng vân canh,Hoài Đức,Hà Nội",
    cityName: "Hà Nội",
    districtName: "Huyện Hoài Đức",
    wardFullName: "Xã Vân Canh",
  },
  {
    displayName: "NGUYEN TRONG TOAN",
    username: "0389090563",
    password: "123456",
    phone: "0389090563",
    address: "2b ngõ 36/282 kim giang,Hoàng Mai,Hà Nội",
    cityName: "Hà Nội",
    districtName: "Quận Hoàng Mai",
    wardFullName: "Phường Đại Kim",
  },
  {
    displayName: "LE VAN KHANH",
    username: "0342011191",
    password: "123456",
    phone: "0342011191",
    address: "Ngọc động - đa tốn - gia lâm - hà nội,Gia Lâm,Hà Nội",
    cityName: "Hà Nội",
    districtName: "Huyện Gia Lâm",
    wardFullName: "Xã Đa Tốn",
  },
  {
    displayName: "TRAN BINH MINH",
    username: "0357537370",
    password: "123456",
    phone: "0357537370",
    address: "Toà nhà NTS, sân bay Nội Bài,Sóc Sơn,Hà Nội",
    cityName: "Hà Nội",
    districtName: "Huyện Sóc Sơn",
    wardFullName: "Thị trấn Sóc Sơn",
  },
  {
    displayName: "LE VIET HUNG",
    username: "0982858966",
    password: "123456",
    phone: "0982858966",
    address: "120 thon1a xa dong my thanh tri hn,Thanh Trì,Hà Nội",
    cityName: "Hà Nội",
    districtName: "Huyện Thanh Trì",
    wardFullName: "Xã Đông Mỹ",
  },
  {
    displayName: "NGUYEN MINH LOC",
    username: "0866918775",
    password: "123456",
    phone: "0866918775",
    address: "17c2 Hàng Quạt, phường Hàng Gai,Hoàn Kiếm,Hà Nội",
    cityName: "Hà Nội",
    districtName: "Quận Hoàn Kiếm",
    wardFullName: "Phường Hàng Gai",
  },
  {
    displayName: "TRAN DINH LUYEN",
    username: "0372099582",
    password: "123456",
    phone: "0372099582",
    address:
      "Khu công nghiệp thị trấn phùng, đan phượng , hà nội,Đan Phượng,Hà Nội",
    cityName: "Hà Nội",
    districtName: "Huyện Đan Phượng",
    wardFullName: "Thị trấn Phùng",
  },
  {
    displayName: "DINH MANH HOAT",
    username: "0986737566",
    password: "123456",
    phone: "0986737566",
    address: "Xưởng giấy tổ 8 thôn xuân sen xã thủy xuân tiên,Chương Mỹ,Hà Nội",
    cityName: "Hà Nội",
    districtName: "Huyện Chương Mỹ",
    wardFullName: "Xã Thủy Xuân Tiên",
  },
  {
    displayName: "NGUYEN THI THUONG",
    username: "0966570650",
    password: "123456",
    phone: "0966570650",
    address: "Khu 2 thôn thọ lão xã tiến thịnh,Mê Linh,Hà Nội",
    cityName: "Hà Nội",
    districtName: "Huyện Mê Linh",
    wardFullName: "Xã Tiến Thịnh",
  },
  {
    displayName: "HOANG QUOC VIET",
    username: "0398291961",
    password: "123456",
    phone: "0398291961",
    address: "Số 7 ngách 27 ngõ 29 Dịch vọng cầu giấy,Cầu Giấy,Hà Nội",
    cityName: "Hà Nội",
    districtName: "Quận Cầu Giấy",
    wardFullName: "Phường Dịch Vọng",
  },
  {
    displayName: "NGU DUY QUY",
    username: "0343969901",
    password: "123456",
    phone: "0343969901",
    address: "218 Đội Cấn, Ba Đình, Hà Nội,Ba Đình,Hà Nội",
    cityName: "Hà Nội",
    districtName: "Quận Ba Đình",
    wardFullName: "Phường Đội Cấn",
  },
  {
    displayName: "NGO SI TAN",
    username: "0865743937",
    password: "123456",
    phone: "0865743937",
    address: "cổng làng nguyên xá -  minh khai-  từ liêm,Bắc Từ Liêm,Hà Nội",
    cityName: "Hà Nội",
    districtName: "Quận Bắc Từ Liêm",
    wardFullName: "Phường Minh Khai",
  },
  {
    displayName: "DUONG MINH QUANG",
    username: "0867918683",
    password: "123456",
    phone: "0867918683",
    address: "171 nguyễn ngọc vũ,Cầu Giấy,Hà Nội",
    cityName: "Hà Nội",
    districtName: "Quận Cầu Giấy",
    wardFullName: "Phường Dịch Vọng Hậu",
  },
  {
    displayName: "BUI VAN SANG",
    username: "0847576066",
    password: "123456",
    phone: "0847576066",
    address: "Xóm ngũ cẩm,Thanh Chương,Tỉnh Nghệ An",
    cityName: "Nghệ An",
    districtName: "Huyện Thanh Chương",
    wardFullName: "Thị trấn Thanh Chương",
  },
  {
    displayName: "NGUYEN TRUONG GIANG",
    username: "0975993515",
    password: "123456",
    phone: "0975993515",
    address: "Thôn 7 diễn kỷ diễn châu nghệ an,Diễn Châu,Tỉnh Nghệ An",
    cityName: "Nghệ An",
    districtName: "Huyện Diễn Châu",
    wardFullName: "Thị trấn Diễn Châu",
  },
  {
    displayName: "NGUYEN HUU THANH",
    username: "0914756523",
    password: "123456",
    phone: "0914756523",
    address: "Khối Hà Long,thị trấn Nam Đàn,Nam Đàn,Tỉnh Nghệ An",
    cityName: "Nghệ An",
    districtName: "Huyện Nam Đàn",
    wardFullName: "Thị trấn Nam Đàn",
  },
  {
    displayName: "NGUYEN ANH NGOC",
    username: "0815192656",
    password: "123456",
    phone: "0815192656",
    address: "84 nguyễn duy trinh phường hưng dũng,Vinh,Tỉnh Nghệ An",
    cityName: "Nghệ An",
    districtName: "Thành phố Vinh",
    wardFullName: "Phường Hưng Dũng",
  },
  {
    displayName: "LE VAN TUONG",
    username: "0981536166",
    password: "123456",
    phone: "0981536166",
    address: "Xóm 2 trung sơn,Đô Lương,Tỉnh Nghệ An",
    cityName: "Nghệ An",
    districtName: "Huyện Đô Lương",
    wardFullName: "Xã Trung Sơn",
  },
  {
    displayName: "DANG KHAC THACH",
    username: "0346460914",
    password: "123456",
    phone: "0346460914",
    address: "Điên lợi diễn châu nghệ an,Diễn Châu,Tỉnh Nghệ An",
    cityName: "Nghệ An",
    districtName: "Huyện Diễn Châu",
    wardFullName: "Xã Diễn Lợi",
  },
  {
    displayName: "PHAM VAN SY",
    username: "0868693273",
    password: "123456",
    phone: "0868693273",
    address: "Xóm trung yên, xã diễn ngọc,Diễn Châu,Tỉnh Nghệ An",
    cityName: "Nghệ An",
    districtName: "Huyện Diễn Châu",
    wardFullName: "Xã Diễn Ngọc",
  },
  {
    displayName: "NGUYEN THI KIEU",
    username: "0969778234",
    password: "123456",
    phone: "0969778234",
    address: "Xóm 1 quỳnh lộc thị xả hoàng mai  nghê an,Quỳnh Lưu,Tỉnh Nghệ An",
    cityName: "Nghệ An",
    districtName: "Huyện Quỳnh Lưu",
    wardFullName: "Xã Ngọc Sơn",
  },
  {
    displayName: "TRAN HUY LAI",
    username: "0947830122",
    password: "123456",
    phone: "0947830122",
    address: "an trụ an thịnh luong tài bác ninh,Bắc Ninh,Tỉnh Bắc Ninh",
    cityName: "Bắc Ninh",
    districtName: "Thành phố Bắc Ninh",
    wardFullName: "Phường Đại Phúc",
  },
  {
    displayName: "VU THI HIEN",
    username: "0869796345",
    password: "123456",
    phone: "0869796345",
    address: "Khu tập thể Vĩnh Xuân mạo khê,Đông Triều,Tỉnh Quảng Ninh",
    cityName: "Quảng Ninh",
    districtName: "Thị xã Đông Triều",
    wardFullName: "Phường Mạo Khê",
  },
  {
    displayName: "LUONG DUC HOAN",
    username: "0983368429",
    password: "123456",
    phone: "0983368429",
    address:
      "Tập thể 314 - phường vàng danh- thành phố uông bí- tỉnh quảng ninh,Uông Bí,Tỉnh Quảng Ninh",
    cityName: "Quảng Ninh",
    districtName: "Thành phố Uông Bí",
    wardFullName: "Phường Bắc Sơn",
  },
  {
    displayName: "TU MINH TRI",
    username: "0834436649",
    password: "123456",
    phone: "0834436649",
    address: "BẤT LỰ HOÀN SƠN,Tiên Du,Tỉnh Bắc Ninh",
    cityName: "Bắc Ninh",
    districtName: "Huyện Tiên Du",
    wardFullName: "Xã Hoàn Sơn",
  },
  {
    displayName: "BUI HUY PHUC",
    username: "0986773287",
    password: "123456",
    phone: "0986773287",
    address: "LÊ hồng phong đông ngàn từ sơn bắc ninh,Từ Sơn,Tỉnh Bắc Ninh",
    cityName: "Bắc Ninh",
    districtName: "Thị xã Từ Sơn",
    wardFullName: "Phường Châu Khê",
  },
  {
    displayName: "LAI VAN BANG",
    username: "0825654416",
    password: "123456",
    phone: "0825654416",
    address:
      "Đường cầu đông Thôn giang liễu xã phương liễu huyện quế võ tỉnh bắc ninh,Quế Võ,Tỉnh Bắc Ninh",
    cityName: "Bắc Ninh",
    districtName: "Huyện Quế Võ",
    wardFullName: "Xã Phương Liễu",
  },
  {
    displayName: "HA DUC LUYEN",
    username: "0937695753",
    password: "123456",
    phone: "0937695753",
    address: "Ấp phước đức a_phước đông,Gò Dầu,Tỉnh Tây Ninh",
    cityName: "Tây Ninh",
    districtName: "Huyện Gò Dầu",
    wardFullName: "Xã Phước Đông",
  },
  {
    displayName: "PHAM THE SON",
    username: "0987271056",
    password: "123456",
    phone: "0987271056",
    address:
      "Số nhà 30_ ngõ 34_ Khu Yên Mẫn _ Phường Kinh Bắc-Tp. Bắc Ninh,Bắc Ninh,Tỉnh Bắc Ninh",
    cityName: "Bắc Ninh",
    districtName: "Thành phố Bắc Ninh",
    wardFullName: "Phường Kinh Bắc",
  },
  {
    displayName: "DINH DUC HUY",
    username: "0984481050",
    password: "123456",
    phone: "0984481050",
    address:
      "Tập thể vĩnh xuân mạo khê đông triều quảng ninh,Đông Triều,Tỉnh Quảng Ninh",
    cityName: "Quảng Ninh",
    districtName: "Thị xã Đông Triều",
    wardFullName: "Phường Mạo Khê",
  },
  {
    displayName: "NGUYEN VAN HAI",
    username: "0398603373",
    password: "123456",
    phone: "0398603373",
    address: "Đại trạch đình tổ,Thuận Thành,Tỉnh Bắc Ninh",
    cityName: "Bắc Ninh",
    districtName: "Thành phố Bắc Ninh",
    wardFullName: "Phường Khắc Niệm",
  },
  {
    displayName: "DAO CONG TUAN",
    username: "0354180886",
    password: "123456",
    phone: "0354180886",
    address: "Số 190 đông ngũ tiên yên quảng ninh,Tiên Yên,Tỉnh Quảng Ninh",
    cityName: "Quảng Ninh",
    districtName: "Huyện Tiên Yên",
    wardFullName: "Xã Đông Ngũ",
  },
  {
    displayName: "HO THANH LIEM",
    username: "0971441477",
    password: "123456",
    phone: "0971441477",
    address:
      "57 đường Huỳnh tấn phát khu phố hiệp bình phường hiệp ninh thành phố Tây ninh,Tây Ninh,Tỉnh Tây Ninh",
    cityName: "Tây Ninh",
    districtName: "Thành phố Tây Ninh",
    wardFullName: "Phường Hiệp Ninh",
  },
  {
    displayName: "HOANG KHAC THUAN",
    username: "0931360323",
    password: "123456",
    phone: "0931360323",
    address:
      "Trường singgapor Đường Hoàng Quốc Việt, Phường Hùng Thắng, Tp Hạ Long,Hạ Long,Tỉnh Quảng Ninh",
    cityName: "Quảng Ninh",
    districtName: "Thành phố Hạ Long",
    wardFullName: "Phường Hùng Thắng",
  },
  {
    displayName: "DHDHSH",
    username: "0977311214",
    password: "123456",
    phone: "0977311214",
    address:
      "44 triệu việt vương- bích đào đông thành, thành phố ninh bình,Ninh Bình,Tỉnh Ninh Bình",
    cityName: "Ninh Bình",
    districtName: "Thành phố Ninh Bình",
    wardFullName: "Phường Đông Thành",
  },
  {
    displayName: "NGUYEN VAN THUY",
    username: "0973927778",
    password: "123456",
    phone: "0973927778",
    address:
      "Khu khe cát.phường minh thành.thị xã Quảng Yên.Tỉnh Quảng Ninh,Quảng Yên,Tỉnh Quảng Ninh",
    cityName: "Quảng Ninh",
    districtName: "Thị xã Quảng Yên",
    wardFullName: "Phường Minh Thành",
  },
  {
    displayName: "DUONG MANH CHUNG",
    username: "0376372976",
    password: "123456",
    phone: "0376372976",
    address: "An giải - đồng kỵ -từ sơn-bắc ninh,Từ Sơn,Tỉnh Bắc Ninh",
    cityName: "Bắc Ninh",
    districtName: "Thị xã Từ Sơn",
    wardFullName: "Phường Đồng Kỵ",
  },
  {
    displayName: "NGUYEN DAC THIN",
    username: "0366376995",
    password: "123456",
    phone: "0366376995",
    address:
      "Thôn giang liễu xã phương liễu huyện Quế Võ tỉnh Bắc Ninh,Quế Võ,Tỉnh Bắc Ninh",
    cityName: "Bắc Ninh",
    districtName: "Huyện Quế Võ",
    wardFullName: "Xã Phương Liễu",
  },
  {
    displayName: "VO DINH HOANG",
    username: "0906504881",
    password: "123456",
    phone: "0906504881",
    address:
      "Hà thanh 2 phường ninh đa thị xã ninh hoà khánh hoà,Ninh Hòa,Tỉnh Khánh Hòa",
    cityName: "Khánh Hòa",
    districtName: "Thị xã Ninh Hòa",
    wardFullName: "Phường Ninh Đa",
  },
  {
    displayName: "LA QUANG CAU",
    username: "0384625616",
    password: "123456",
    phone: "0384625616",
    address:
      "Thôn đống am xã thuỷ đường thuỷ nguyên thành phố hải phòng,Thủy Nguyên,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Thủy Nguyên",
    wardFullName: "Thủy Dường",
  },
  {
    displayName: "PHAM VAN DUY",
    username: "0328875536",
    password: "123456",
    phone: "0328875536",
    address: "xuan lai,Tiên Lãng,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Tiên Lãng",
    wardFullName: "Xuân Lai",
  },
  {
    displayName: "BUI HAI HUNG",
    username: "0796371665",
    password: "123456",
    phone: "0796371665",
    address: "An lư thủy nguyên hải phòng,Thủy Nguyên,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Thủy Nguyên",
    wardFullName: "An Lư",
  },
  {
    displayName: "VUONG QUOC HUY",
    username: "0563460578",
    password: "123456",
    phone: "0563460578",
    address: "Lô 27 m2a,Ngô Quyền,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Ngô Quyền",
    wardFullName: "Ngô Quyền",
  },
  {
    displayName: "HUYNH NGOC HOANG",
    username: "0562963537",
    password: "123456",
    phone: "0562963537",
    address:
      "156 lô 27 đường lê hồng phong phường đông khê,Ngô Quyền,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Ngô Quyền",
    wardFullName: "Đông Khê",
  },
  {
    displayName: "HUYNH THI HA",
    username: "0377343033",
    password: "123456",
    phone: "0377343033",
    address:
      "Sanh toa nha m5 khu 9 tang lo27 duong le hong phong phuong dong khe,Ngô Quyền,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Ngô Quyền",
    wardFullName: "Đông Khê",
  },
  {
    displayName: "VO KIEU",
    username: "0367139177",
    password: "123456",
    phone: "0367139177",
    address: "Sô 177 nguyễn hưu tuệ,Ngô Quyền,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Ngô Quyền",
    wardFullName: "Đông Khê",
  },
  {
    displayName: "NGUYEN THANH LUAN",
    username: "0961583953",
    password: "123456",
    phone: "0961583953",
    address: "M2b,Ngô Quyền,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Ngô Quyền",
    wardFullName: "Đông Khê",
  },
  {
    displayName: "LUC THI MAI PHUONG",
    username: "0911287145",
    password: "123456",
    phone: "0911287145",
    address:
      "Toa nha m2b khu 9 tang lo 27 duong le hong phong,Ngô Quyền,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Ngô Quyền",
    wardFullName: "Đông Khê",
  },
  {
    displayName: "TRAN TRONG NGUYEN",
    username: "0385235723",
    password: "123456",
    phone: "0385235723",
    address: "99 m5 lo 27,Ngô Quyền,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Ngô Quyền",
    wardFullName: "Đông Khê",
  },
  {
    displayName: "DOAN VAN KHUONG",
    username: "0978982977",
    password: "123456",
    phone: "0978982977",
    address:
      "Thôn vân kì xã bắc hưng huyện tiên lãng tp hải phòng,Tiên Lãng,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Tiên Lãng",
    wardFullName: "Bắc Hưng",
  },
  {
    displayName: "DO KIM LUYEN",
    username: "0946849514",
    password: "123456",
    phone: "0946849514",
    address: "14/16/20 tôn đức thắng lê chân hải phòng,Lê Chân,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Lê Chân",
    wardFullName: "An Dương",
  },
  {
    displayName: "TRAN THANH PHI",
    username: "0563459891",
    password: "123456",
    phone: "0563459891",
    address: "99 cuoi ngo 71 dong khe,Ngô Quyền,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Ngô Quyền",
    wardFullName: "Đông Khê",
  },
  {
    displayName: "NGUYEN THANH BINH",
    username: "0906100494",
    password: "123456",
    phone: "0906100494",
    address: "Thôn trại xã thuỷ đường,Thủy Nguyên,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Thủy Nguyên",
    wardFullName: "Thủy Dường",
  },
  {
    displayName: "NGUYEN VAN QUANG",
    username: "0349162811",
    password: "123456",
    phone: "0349162811",
    address: "Trường thọ,An Lão,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "An Lão",
    wardFullName: "Trường Thọ",
  },
  {
    displayName: "NGUYEN QUOC HUY",
    username: "0563436544",
    password: "123456",
    phone: "0563436544",
    address: "99 lô27 dong khe,Ngô Quyền,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Ngô Quyền",
    wardFullName: "Đông Khê",
  },
  {
    displayName: "PHAM ANH DAI",
    username: "0925773293",
    password: "123456",
    phone: "0925773293",
    address:
      "88 lo 26 bc duong le hong phong phuong dong khe,Ngô Quyền,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Ngô Quyền",
    wardFullName: "Đông Khê",
  },
  {
    displayName: "NGUYEN TUNG LAM",
    username: "0779998222",
    password: "123456",
    phone: "0779998222",
    address:
      "Công ty Rorze Robotech - khu công nghiệp Nomura - Huyện An Dương - Thành Phố Hải Phòng,An Dương,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "An Dương",
    wardFullName: "An Dồng",
  },
  {
    displayName: "NGO VAN TUONG",
    username: "0565239343",
    password: "123456",
    phone: "0565239343",
    address:
      "So nha 9b toa nha M5 khu tang 9  lo 27 duong le hong phong,Ngô Quyền,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Ngô Quyền",
    wardFullName: "Đông Khê",
  },
  {
    displayName: "PHAM VAN TAO",
    username: "0783107829",
    password: "123456",
    phone: "0783107829",
    address: "Xom4 tam hung,Thủy Nguyên,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Thủy Nguyên",
    wardFullName: "Tam Hưng",
  },
  {
    displayName: "HOANG VAN NHAN",
    username: "0563438954",
    password: "123456",
    phone: "0563438954",
    address: "67 lo 26 bc duong le hong phuong dong khe,Ngô Quyền,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Ngô Quyền",
    wardFullName: "Đông Khê",
  },
  {
    displayName: "PHAM VIET ANH",
    username: "0936933992",
    password: "123456",
    phone: "0936933992",
    address: "368 Hùng Vương Sở Dầu,Hồng Bàng,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Hồng Bàng",
    wardFullName: "Sở Dầu",
  },
  {
    displayName: "NGUYEN THI NHUNG",
    username: "0978802734",
    password: "123456",
    phone: "0978802734",
    address: "368 Hùng Vương Sở Dầu,Hồng Bàng,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Hồng Bàng",
    wardFullName: "Sở Dầu",
  },
  {
    displayName: "VU VAN MANH",
    username: "0347841308",
    password: "123456",
    phone: "0347841308",
    address: "Tiên cường,Tiên Lãng,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Tiên Lãng",
    wardFullName: "Tiên Cường",
  },
  {
    displayName: "NGUYEN MINH NGUYET",
    username: "0589837483",
    password: "123456",
    phone: "0589837483",
    address:
      "So 345 lô 27 đường lê hồng phong phường đông khê,Ngô Quyền,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Ngô Quyền",
    wardFullName: "Đông Khê",
  },
  {
    displayName: "DAO XUAN TAM",
    username: "0904424369",
    password: "123456",
    phone: "0904424369",
    address: "Thôn 6 Bắc Sơn,An Dương,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "An Dương",
    wardFullName: "Bắc Sơn",
  },
  {
    displayName: "LE VAN GIANG",
    username: "0968627293",
    password: "123456",
    phone: "0968627293",
    address:
      "97 Thuỷ Giang - Hải Thành- Dương Kinh - Hải Phòng,Dương Kinh,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Dương Kinh",
    wardFullName: "Hải Thành",
  },
  {
    displayName: "NGUYEN DINH CONG",
    username: "0794155907",
    password: "123456",
    phone: "0794155907",
    address: "Xa dương quan - thuỷ nguyên - hải phòng,Thủy Nguyên,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Thủy Nguyên",
    wardFullName: "Dường Quan",
  },
  {
    displayName: "NGUYEN THI QUAN",
    username: "0563452699",
    password: "123456",
    phone: "0563452699",
    address: "78 lo 26 duong le hong phong phuong dong khe,Ngô Quyền,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Ngô Quyền",
    wardFullName: "Đông Khê",
  },
  {
    displayName: "LUU THI MINH TRANG",
    username: "0796005470",
    password: "123456",
    phone: "0796005470",
    address: "9H xóm trại, trà khê 1, anh dũng,Dương Kinh,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Dương Kinh",
    wardFullName: "An Dũng",
  },
  {
    displayName: "NGUYEN DUC NGUYEN",
    username: "0563439514",
    password: "123456",
    phone: "0563439514",
    address:
      "45 lo 26 bc duong le hong phong phuong dong khe,Ngô Quyền,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Ngô Quyền",
    wardFullName: "Đông Khê",
  },
  {
    displayName: "TRAN NHU TRONG",
    username: "0563244312",
    password: "123456",
    phone: "0563244312",
    address:
      "123 lo 27 đuong le hong phong phuong dong khe,Ngô Quyền,Hải Phòng",
    cityName: "Hải Phòng",
    districtName: "Ngô Quyền",
    wardFullName: "Đông Khê",
  },
  {
    displayName: "NGUYEN DAI THANG",
    username: "0964044168",
    password: "123456",
    phone: "0964044168",
    address: "Thôn ngòi hóp xã báo đáp,Trấn Yên,Tỉnh Yên Bái",
    cityName: "Yên Bái",
    districtName: "Trấn Yên",
    wardFullName: "Báo Đáp",
  },
  {
    displayName: "NGUYEN QUOC HUY",
    username: "0386012522",
    password: "123456",
    phone: "0386012522",
    address:
      "salon huy nguyễn- Thôn hà chợ-xã thái dương-bình giang- hải dương,Bình Giang,Tỉnh Hải Dương",
    cityName: "Hải Dương",
    districtName: "Bình Giang",
    wardFullName: "Thái Dương",
  },
  {
    displayName: "PHAM VAN GIANG",
    username: "0388167258",
    password: "123456",
    phone: "0388167258",
    address:
      "257 NGUYỄN ĐẠI NĂNG P. AN LƯU TX. KINH MÔN HẢI DƯƠNG,Kinh Môn,Tỉnh Hải Dương",
    cityName: "Hải Dương",
    districtName: "Kinh Môn",
    wardFullName: "An Lưu",
  },
  {
    displayName: "LE THI NGAN",
    username: "0974806195",
    password: "123456",
    phone: "0974806195",
    address: "Bùi thượng gia lộc Hải dương,Gia Lộc,Tỉnh Hải Dương",
    cityName: "Hải Dương",
    districtName: "Gia Lộc",
    wardFullName: "Yết Kiêu",
  },
  {
    displayName: "DUONG VAN CUONG",
    username: "0337392589",
    password: "123456",
    phone: "0337392589",
    address: "xã liên mạc,Kim Thành,Tỉnh Hải Dương",
    cityName: "Hải Dương",
    districtName: "Kim Thành",
    wardFullName: "Liên Mạc",
  },
  {
    displayName: "DUONG VIET HONG",
    username: "0943656656",
    password: "123456",
    phone: "0943656656",
    address: "38 hải hưng, ecorivers, p. Hải tân,Hải Dương,Tỉnh Hải Dương",
    cityName: "Hải Dương",
    districtName: "Hải Tân",
    wardFullName: "Hải tân",
  },
  {
    displayName: "LUU VAN DUC",
    username: "0372685929",
    password: "123456",
    phone: "0372685929",
    address:
      "Thôn kim định xã đại đức huyện kim thành tình hải dương,Kim Thành,Tỉnh Hải Dương",
    cityName: "Hải Dương",
    districtName: "Kim Thành",
    wardFullName: "Kim Thành",
  },
  {
    displayName: "DINH HO DAT",
    username: "0826211104",
    password: "123456",
    phone: "0826211104",
    address: "Khu 5 phường Cẩm thượng,Hải Dương,Tỉnh Hải Dương",
    cityName: "Hải Dương",
    districtName: "Hải Dương",
    wardFullName: "Cẩm Thượng",
  },
  {
    displayName: "VU THI YEN",
    username: "0962814746",
    password: "123456",
    phone: "0962814746",
    address:
      "Số 5 nguyễn lương bằng bình hàn tp hải dương,Hải Dương,Tỉnh Hải Dương",
    cityName: "Hải Dương",
    districtName: "TP Hải Dương",
    wardFullName: "Bình Hàn",
  },
  {
    displayName: "DINH THI PHUONG THUY",
    username: "0987678381",
    password: "123456",
    phone: "0987678381",
    address:
      "số 28 vũ văn mật đông nam cường thành phố hải dương phường hải tân,Hải Dương,Tỉnh Hải Dương",
    cityName: "Hải Dương",
    districtName: "Hải Dương",
    wardFullName: "Hải Tân",
  },
  {
    displayName: "BUI THI THU TRANG",
    username: "0934640372",
    password: "123456",
    phone: "0934640372",
    address:
      "SỐ 28 PHỐ VŨ VĂN MẬT ĐÔNG NAM CƯỜNG PHƯỜNG HẢI TÂN TP HẢI DƯƠNG,Hải Dương,Tỉnh Hải Dương",
    cityName: "Hải Dương",
    districtName: "TP Hải Dương",
    wardFullName: "Hải tân",
  },
  {
    displayName: "CHU THANH GIANG",
    username: "0379170093",
    password: "123456",
    phone: "0379170093",
    address: "Cty Shinheung vina,Hải Dương,Tỉnh Hải Dương",
    cityName: "Hải Dương",
    districtName: "Hải Dương",
    wardFullName: "Ngọc Châu",
  },
  {
    displayName: "VU VAN TUAN",
    username: "0332413880",
    password: "123456",
    phone: "0332413880",
    address: "215 Vạn Đức,Kinh Môn,Tỉnh Hải Dương",
    cityName: "Hải Dương",
    districtName: "Kinh Môn",
    wardFullName: "An Sinh",
  },
  {
    displayName: "VU XUAN ANH",
    username: "0343247066",
    password: "123456",
    phone: "0343247066",
    address:
      "Thôn đông giao xã lương điền huyện cẩm giàng tỉnh hải dương,Cẩm Giàng,Tỉnh Hải Dương",
    cityName: "Hải Dương",
    districtName: "Cẩm Giàng",
    wardFullName: "Lương Điền",
  },
  {
    displayName: "NGUYEN THI HUYEN",
    username: "0384748356",
    password: "123456",
    phone: "0384748356",
    address:
      "Bùi Xá -  Nhấn Quyền - Bình Giang - Hải Dương,Bình Giang,Tỉnh Hải Dương",
    cityName: "Hải Dương",
    districtName: "Bình Giang",
    wardFullName: "Vĩnh Hưng",
  },
  {
    displayName: "LE VAN TRUYEN",
    username: "0388616118",
    password: "123456",
    phone: "0388616118",
    address:
      "chùa sơn đình 2 thanh lâm lục nam bắc giang,Lục Nam,Tỉnh Bắc Giang",
    cityName: "Bắc Giang",
    districtName: "Lục Nam",
    wardFullName: "đông Hưng",
  },
  {
    displayName: "DAO TUAN MINH",
    username: "0916833969",
    password: "123456",
    phone: "0916833969",
    address: "Số 08, đường 19/5, thị trấn thắng,Hiệp Hòa,Tỉnh Bắc Giang",
    cityName: "Bắc Giang",
    districtName: "Hiệp Hòa",
    wardFullName: "đồng Tân",
  },
  {
    displayName: "NGUYEN VAN QUYEN",
    username: "0987646264",
    password: "123456",
    phone: "0987646264",
    address: "Đức Thịnh Trí Yên Yên Dũng Bắc Giang,Yên Dũng,Tỉnh Bắc Giang",
    cityName: "Bắc Giang",
    districtName: "Yên Dũng",
    wardFullName: "Yên Lư",
  },
];
function subtractMonths(date) {
  date.setMonth(date.getMonth() - Math.floor(Math.random() * 2));
  return date;
}
export const userTool = async (req, res, next) => {
  try {
    const total = (products) => {
      let total = 0;
      products.map((item) => {
        total += item.quantity * item.currentPrice;
      });
      return total;
    };
    Promise.all(
      users.map(async (i) => {
        const myDate = subtractMonths(new Date());
        const productIndex = Math.floor(Math.random() * 140 + 1);
        const day = Math.floor(Math.random() * 27);
        // const user = await User.find({ username: i.username });
        const product = products[productIndex];
        console.log(product);
        // const p = await Product.findByIdAndUpdate(product._id, {
        //   $inc: { outStock: 1 },
        // });
        if (product) {
          const user = await User.findOne({ username: i.username });
          await Product.findByIdAndUpdate(product._id, {
            $inc: { outStock: 1 },
          });
          const newOrder = new Order({
            orderNumber: new Date().getTime(),
            buyerId: user._id,
            buyerName: i.displayName,
            buyerPhone: i.phone,
            toCity: i.cityName,
            toDistrict: i.districtName,
            toWard: i.wardFullName,
            toAddress: i.address,
            total: product.currentPrice + [20000, 35000][Math.random() * 2],
            status: 2,
            products: [
              {
                id: product._id,
                productName: product.productName,
                description: product.description,
                currentPrice: product.currentPrice,
                shopID: product.shopID,
                shopName: product.shopName || "Sale168.vn",
                img: product.imgs[0],
                quantity: 1,
              },
            ],
            createdAt: myDate,
            tracking: [
              {
                status: 0,
                desc: "tạo đơn thành công",
                time: myDate.setDate(day),
              },
              {
                status: 1,
                desc: "Thay đổi trạng thái đơn hàng",
                time: myDate.setDate(day + Math.floor(Math.random() * 2)),
              },
              {
                status: 2,
                desc: "Thay đổi trạng thái đơn hàng",
                time: myDate.setDate(day + Math.floor(Math.random() * 5)),
              },
            ],
          });
          //   console.log(newOrder);
          await newOrder.save();
        }
      })
    );

    res.status(200).json("done");
  } catch (error) {
    next(error);
  }
};
